name: E2E Test
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  E2E:
    name: E2E
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "22.12.0"

      - name: Install package
        run: pnpm install

      - name: Install Playwright Browser
        run: pnpm playwright install

      - name: Run E2E Test
        run: pnpm test:e2e
